online_course/online_course/urls.py
from django.urls import path, re_path
from . import views

app_name = "online_course"
urlpatterns = [
    path(route="", view=views.CourseListView.as_view(), name="index"),
    re_path(r"^(?!admin/).*login/.*$", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLoginView.as_view(), name="logout"),
    path("registration/", views.UserRegistrationView.as_view(), name="registration"),
    path(
        "course_details/<int:pk>/",
        views.CourseDetailsView.as_view(),
        name="course_details",
    ),
    path("enroll/<int:course_id>/", views.EnrollmentView.as_view(), name="enroll"),
    path("course/<int:course_id>/submit", view=views.submit, name="submit"),
    path(
        "course/<int:course_id>/exam_result",
        view=views.get_exam_result,
        name="exam_result",
    ),
]

online_course/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("online_course.urls")),
    path("admin/", admin.site.urls),
]

online_course/online_course/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now


# Learner model
class Learner(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    STUDENT = "student"
    DEVELOPER = "developer"
    DATA_SCIENTIST = "data_scientist"
    DATABASE_ADMIN = "dba"
    OCCUPATION_CHOICES = [
        (STUDENT, "Student"),
        (DEVELOPER, "Developer"),
        (DATA_SCIENTIST, "Data Scientist"),
        (DATABASE_ADMIN, "Database Admin"),
    ]
    occupation = models.CharField(
        null=False, max_length=20, choices=OCCUPATION_CHOICES, default=STUDENT
    )
    social_link = models.URLField(max_length=200)

    def __str__(self):
        return self.user.username + "," + self.occupation


# Instructor model
class Instructor(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()

    def __str__(self):
        return self.user.username


# Course model
class Course(models.Model):
    name = models.CharField(null=False, max_length=30, default="new course")
    image = models.ImageField(upload_to="")
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through="Enrollment")
    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False

    def __str__(self):
        return "Name: " + self.name + "," + "Description: " + self.description


# Enrollment model
class Enrollment(models.Model):
    AUDIT = "audit"
    HONOR = "honor"
    BETA = "BETA"
    COURSE_MODES = [(AUDIT, "Audit"), (HONOR, "Honor"), (BETA, "BETA")]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)

    def __str__(self):
        return (
            "Enrollment: "
            + str(self.pk)
            + ","
            + "Course: "
            + str(self.course.description)
        )


# Lesson model
class Lesson(models.Model):
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()


# Question model
class Question(models.Model):
    lesson = models.ForeignKey(Course, on_delete=models.CASCADE)
    question_text = models.TextField(null=False)
    grade = models.IntegerField(default=0)


# Choice model
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField(null=False)
    is_correct = models.BooleanField(default=False)


# Submission model
class Submission(models.Model):
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    choices = models.ManyToManyField(Choice)
    created_at = models.DateTimeField(default=now)

    def __str__(self):
        return "Submission: " + str(self.pk)

online_course/online_course/forms.py
from django import forms


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=3)
    first_name = forms.CharField(max_length=20, min_length=3)
    last_name = forms.CharField(max_length=20, min_length=3)
    password = forms.PasswordInput(render_value=False)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=3)
    password = forms.PasswordInput(render_value=False)

online_course/online_course/views.py
from functools import reduce
from django import forms
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse
from django.views import generic

from .forms import LoginForm, RegistrationForm
from .models import Choice, Course, Enrollment, Submission


def check_if_enrolled(user, course):
    is_enrolled = False
    if user.id is not None:
        num_results = Enrollment.objects.filter(user=user, course=course).count()
        if num_results > 0:
            is_enrolled = True
    return is_enrolled


def get_choices(choices, is_correct):
    return list(filter(lambda ch: ch["is_correct"] == is_correct, choices))


# User registration
class UserRegistrationView(generic.View):
    initial = {}
    form_class = RegistrationForm
    template_name = "online_course/registration.html"

    def get(self, request):
        user = self.request.user
        if user.is_authenticated:
            return redirect("online_course:index")
        return render(request, self.template_name)

    def post(self, request):
        form = self.form_class(request.POST)
        if not form.is_valid():
            messages.error(request, message="Invalid form data.")
            return redirect("online_course:registration")

        username = request.POST.get("username")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        password = request.POST.get("password")

        try:
            user = User.objects.create_user(
                username=username,
                first_name=first_name,
                last_name=last_name,
                password=password,
            )
            login(request, user)
            return redirect("online_course:index")
        except:
            messages.error(request, message="User already exists")
            return redirect("online_course:registration")


# User login
class UserLoginView(generic.View):
    initial = {}
    form_class = LoginForm
    template_name = "online_course/login.html"

    def get(self, request):
        logout(request)
        if "logout" in request.path:
            return redirect("online_course:index")
        return render(request, self.template_name)

    def post(self, request):
        form = self.form_class(request.POST)
        if not form.is_valid():
            messages.error(request, message="Invalid form data.")
            return redirect("online_course:registration")

        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return redirect("online_course:index")
        else:
            messages.error(request, message="Invalid username or/and password.")
            return redirect("online_course:login")


# CourseListView
class CourseListView(generic.ListView):
    model = Course
    template_name = "online_course/courses.html"
    context_object_name = "course_list"

    def get_queryset(self):
        user = self.request.user
        courses = self.model.objects.order_by("-total_enrollment")[:10]  # type: ignore
        for course in courses:
            if user.is_authenticated:
                course.is_enrolled = check_if_enrolled(user, course)  # type: ignore
        return courses


# Course detail view
class CourseDetailsView(generic.DetailView):
    model = Course
    template_name = "online_course/course_details.html"

    @method_decorator(login_required)
    def get(self, request, pk):
        user = self.request.user
        course, *_ = self.model.objects.filter(id=pk).select_related()
        is_enrolled = check_if_enrolled(user, course)

        if not is_enrolled:
            return redirect("online_course:index")
        return render(request, self.template_name, {"course": course, "questions": course.question_set.all()})  # type: ignore


# Enrollment view
class EnrollmentView(generic.View):
    form_class = forms.Form

    @method_decorator(login_required)
    def post(self, request, course_id):
        course = get_object_or_404(Course, pk=course_id)
        user = request.user

        is_enrolled = check_if_enrolled(user, course)
        if not is_enrolled and user.is_authenticated:
            Enrollment.objects.create(user=user, course=course, mode="honor")
            course.total_enrollment += 1
            course.save()

        return HttpResponseRedirect(
            reverse(viewname="online_course:course_details", args=(course.pk,))
        )


# Submit exam
@login_required
def submit(request, course_id):
    user = request.user
    form_data = dict(request.POST)

    enrollment = Enrollment.objects.get(course_id=course_id, user=user)

    submission = Submission.objects.create(enrollment=enrollment)
    choices_ids = []
    for choice in form_data.items():
        if len(choice[1]) and choice[1][0] == "on":
            choices_ids.append(choice[0])

    choices = Choice.objects.filter(pk__in=choices_ids)
    submission.choices.set(choices)
    return redirect("online_course:exam_result", course_id=course_id)


# Exam result
@login_required
def get_exam_result(request, course_id):
    user = request.user
    enrollment, *_ = Enrollment.objects.filter(
        user=user, course_id=course_id
    ).select_related()
    submission = enrollment.submission_set.order_by("-created_at")[0]  # type: ignore
    choices = submission.choices.all()

    course, *__ = Course.objects.filter(pk=course_id).select_related()
    questions = list(set(map(lambda ch: ch.question, choices)))

    if len(course.question_set.all()) > len(questions):  # type: ignore
        messages.error(request, message="Please answer all questions")
        return redirect("online_course:course_details", pk=course_id)

    choice_grades = 0
    results = {}

    for question in questions:
        question_choices = question.choice_set.all()
        truthy_choices = get_choices(question_choices.values(), True)
        falsy_choices = get_choices(question_choices.values(), False)

        submitted_choices = list(
            filter(lambda ch: ch.question_id == question.id, choices)
        )

        for choice in submitted_choices:
            if choice.is_correct:
                if not question.id in results:
                    results[question.id] = {
                        "question_id": question.id,
                        "question_text": question.question_text,
                        "truthy_choices": [choice],
                        "falsy_choices": falsy_choices,
                    }
                else:
                    results[question.id]["truthy_choices"].append(choice)

                choice_grades += question.grade / len(truthy_choices)
            else:
                falsy_answer = list(
                    filter(lambda f_ch: f_ch["id"] == choice.id, falsy_choices)
                )
                if len(falsy_answer):
                    falsy_answer[0]["checked"] = True
                if not question.id in results:
                    results[question.id] = {
                        "question_id": question.id,
                        "question_text": question.question_text,
                        "truthy_choices": [],
                        "falsy_choices": falsy_choices,
                    }
                choice_grades -= question.grade / len(falsy_choices)

        if "truthy_choices" in results[question.id] and len(truthy_choices) > len(
            results[question.id]["truthy_choices"]
        ):
            results[question.id]["unchecked_choices"] = list(
                filter(
                    lambda choice: choice["id"]
                    not in map(lambda r: r.id, results[question.id]["truthy_choices"]),
                    truthy_choices,
                )
            )

    max_grade = reduce(
        lambda _, curr: 0 + curr, list(map(lambda q: q.grade, questions))
    )
    grade_percentage = (
        0
        if choice_grades <= 0
        else round((100 * choice_grades) / (max_grade * len(questions)))
    )

    return render(
        request,
        "online_course/exam_result.html",
        {
            "course": {"id": enrollment.course.pk, "name": enrollment.course.name},
            "results": results.values(),
            "grade": grade_percentage,
        },
    )

online_course/online_course/templates/online_course/_exam_form.html
{% block exam_form %}

<button class="btn btn-primary btn-block" data-toggle="collapse" data-target="#exam">
  Start Exam
</button>
<div id="exam" class="collapse">
  <form action="{% url 'online_course:submit' course.id %}" method="post">
    {% csrf_token %}
    <!-- questions -->
    {% for question in questions %}
    <div id="question__{{ question.id }}" class="card mt-1">
      <div class="card-header">
        <h5 style="display: inline-block; width: 80%">{{ question.question_text }}</h5>
        <p style="display: inline-block; text-align: right">Grade: {{ question.grade }} point(s)</p>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-numbered">
          {% for choice in question.choice_set.all %}
          <li class="list-group-item">
            <div class="form-check">
              <input
                class="form-check-input question__{{ question.id }}"
                type="checkbox"
                name="{{ choice.id }}"
                id="{{ choice.id }}"
              />
              <label class="form-check-label" for="{{ choice.id }}">
                {{ choice.choice_text }}
              </label>
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    {% endfor %}
    <button id="submit-exam" class="btn btn-success form-control submit-exam" type="submit">
      Submit
    </button>
  </form>
</div>
{% endblock %}

online_course/online_course/templates/online_course/base.html
<!DOCTYPE html>

<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'online_course/assets/dj_icon.png' %}" type="image/x-icon" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'online_course/styles/online_course.css' %}"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'online_course/scripts/online_course.js' %}"></script>
    <title>Online course app: {% block title %}{{ title }}{% endblock %}</title>
  </head>

  <body>
    <!-- base header -->
    <header>
      <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'online_course:index' %}">
              <h4>Home</h4>
            </a>
          </div>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
              <a
                style="font-size: 1.1rem"
                class="btn btn-link"
                href="{% url 'online_course:index' %}"
                >{{user.first_name}}({{user.username}})</a
              >
              <a
                style="font-size: 1.1rem"
                class="btn btn-link"
                href="{% url 'online_course:logout' %}"
                >Logout</a
              >
            </li>
            {% else %}
            <li>
              <a
                style="font-size: 1.1rem"
                class="btn {% if request.resolver_match.url_name == 'login' %}btn-link disabled{% else %}btn-primary{% endif %}"
                href="{% url 'online_course:login' %}"
              >
                Login
              </a>
              <a
                style="font-size: 1.1rem"
                class="btn {% if request.resolver_match.url_name == 'registration' %}btn-link disabled{% else %}btn-link{% endif %}"
                href="{% url 'online_course:registration' %}"
              >
                Sign Up
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <!-- block registration -->
      {% block registration %}{% endblock %}
      <!-- block registration -->
      {% block login %}{% endblock %}
      <!-- block courses -->
      {% block courses %}{% endblock %}
      <!-- block course details -->
      {% block course_details %}{% endblock %}
      <!-- exam form  -->
      {% block exam_form %}{% endblock %}
      <!-- exam result -->
      {% block exam_result %}{% endblock %}
    </main>
  </body>
</html>

online_course/online_course/templates/online_course/course_details.html
{% extends "online_course/base.html" %}

<!-- title -->
{% block title %} {{ course.name }} {% endblock %}
<!-- course -->
{% block course_details %}
<!-- Course details -->
<div class="container-fluid course-details">
  {% for message in messages %}
  <div class="alert alert-danger">{{ message }}</div>
  {% endfor %}
  <h2>{{ course.description }}</h2>
  <hr />
  <div class="card-columns-vertical">
    {% for lesson in course.lesson_set.all %}
    <div class="card mt-1">
      <div class="card-header">
        <h5>Lesson {{ lesson.order|add:1 }}: {{ lesson.title }}</h5>
      </div>
      <div class="card-body">{{ lesson.content }}</div>
    </div>
    {% endfor %}
  </div>
  <!-- exam form -->
  {% if user.is_authenticated %}
  <div>{% include "online_course/_exam_form.html" %}</div>
  {% endif %}
</div>
{% endblock %}

online_course/online_course/templates/online_course/courses.html
{% extends "online_course/base.html" %}

<!-- static -->
{% load static %}
<!-- title -->
{% block title %} Course list {% endblock %}
<!-- courses -->
{% block courses %} {% if course_list %}
<div class="container courses">
  <h2>Courses</h2>
  <hr />
  <div class="card-deck">
    {% for course in course_list %}
    <div class="card mb-3">
      <img
        class="card-img"
        src="{% static 'online_course/media/' %}{{ course.image }}"
        alt="Course image"
      />
      <div class="card-body bg-light">
        <h5 class="card-title">
          {{ course.name }},
          <span class="text-success"> {{ course.total_enrollment}} enrolled</span>
        </h5>
        <p class="card-text">{{ course.description}}</p>
      </div>
      <div class="enroll">
        <form action="{% url 'online_course:enroll' course.id %}" method="post">
          {% csrf_token %}
          <input
            class="btn btn-primary form-control"
            type="submit"
            value="{% if course.is_enrolled %}Enter{% else %}Enroll{% endif %} "
          />
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% else %}
<p>No courses are available.</p>
{% endif %} {% endblock %}

online_course/online_course/templates/online_course/exam_result.html
{% extends "online_course/base.html" %}

<!-- title -->
{% block title %} Exam result {% endblock %}
<!-- exam result -->
{% block exam_result %}
<div class="container-fluid">
  <h4>Course: {{ course.name }}</h4>
  {% if grade > 80 %}
  <div class="alert alert-success">
    <strong>Congratulations, {{ user.first_name }}!&nbsp;</strong>You have passed the exam and
    completed the course with score {{ grade }}/100
  </div>
  {% else %}
  <div class="alert alert-danger">
    <strong>Failed&nbsp;</strong>
    Sorry, {{ user.first_name }}! You have failed exam with score {{ grade }}/100
  </div>
  <a class="btn btn-link text-danger" href="{% url 'online_course:course_details' course.id %}"
    >Re-test</a
  >
  {% endif %}
  <div class="card-columns-vertical mt-1">
    <h5>Exam results</h5>
    {% for result in results %}
    <div class="card mt-1">
      <div class="card-header">
        <h5>{{ result.question_text }}</h5>
      </div>
      <div class="card-body">
        <!-- correct choices -->
        {% for correct_choice in result.truthy_choices %}
        <p class="correct-text">
          <strong>Correct answer: {{ correct_choice.choice_text }}</strong>
        </p>
        {% endfor %}
        <!-- incorrect choices -->
        {% for incorrect_choice in result.falsy_choices %} {% if incorrect_choice.checked %}
        <p class="incorrect-text">
          <strong>Incorrect answer: {{ incorrect_choice.choice_text }}</strong>
        </p>
        {% else %}
        <p>
          <strong>{{ incorrect_choice.choice_text }}</strong>
        </p>
        {% endif %} {% endfor %}
        <!-- unchecked choices -->
        {% for unchecked_choice in result.unchecked_choices %}
        <p class="unchecked-text">
          <strong>Not selected: {{ unchecked_choice.choice_text }}</strong>
        </p>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

online_course/online_course/templates/online_course/login.html
{% extends "online_course/base.html" %}

<!-- title -->
{% block title %} Login {% endblock %}
<!-- login -->
{% block login %}
<form action="{% url 'online_course:login' %}" method="post">
  {% csrf_token %}
  <div class="container">
    <h1>Login</h1>
    <hr />
    <div class="form-group">
      <label for="username"><b>User Name</b></label>
      <input
        id="username"
        class="form-control"
        type="text"
        placeholder="Enter User Name:"
        name="username"
        minlength="3"
        maxlength="20"
        required
      />
      <label for="password"><b>Password</b></label>
      <input
        id="password"
        class="form-control"
        type="password"
        placeholder="Enter Password:"
        name="password"
        minlength="8"
        maxlength="20"
        required
      />
      {% if messages %}
      <div class="alert alert-danger">{% for message in messages %} {{ message }} {% endfor %}</div>
      {% endif %}
      <button class="btn btn-primary" type="submit">Login</button>
    </div>
  </div>
</form>
{% endblock %}

online_course/online_course/templates/online_course/registration.html
{% extends "online_course/base.html" %}

<!-- title -->
{% block title %} Registration {% endblock %}
<!-- courses -->
{% block registration %}
<!-- Stylize Registration form -->
<form action="{% url 'online_course:registration' %}" method="post">
  <div class="container">
    {% csrf_token %}
    <h1>Sign Up</h1>
    <hr />
    <div class="form-group">
      <label for="username"><b>User Name</b></label>
      <input
        id="username"
        type="text"
        class="form-control"
        placeholder="Enter User Name: "
        name="username"
        minlength="3"
        maxlength="20"
        required
      />
      <label for="first_name"><b>First Name</b></label>
      <input
        id="first_name"
        type="text"
        class="form-control"
        placeholder="Enter First Name: "
        name="first_name"
        minlength="3"
        maxlength="20"
        required
      />
      <label for="last_name"><b>Last Name</b></label>
      <input
        id="last_name"
        type="text"
        class="form-control"
        placeholder="Enter Last Name: "
        name="last_name"
        minlength="3"
        maxlength="20"
        required
      />
      <label for="password"><b>Password</b></label>
      <input
        id="password"
        type="password"
        class="form-control"
        placeholder="Enter Password: "
        name="password"
        minlength="8"
        maxlength="20"
        required
      />
      {% if messages %}
      <div class="alert alert-danger">{% for message in messages %} {{ message }} {% endfor %}</div>
      {% endif %}
      <button class="btn btn-primary" type="submit">Sign up</button>
    </div>
  </div>
</form>
{% endblock %}